# Generated by Django 5.2.17 on 2026-09-24 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('allows_negative_balance', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('allows_negative_balance', True), ('handle', 'EXTERNAL_FUNDING'), ('id', uuid.UUID('00000000-0000-0000-0000-000000000001'))), models.Q(models.Q(('id', uuid.UUID('00000000-0000-0000-0000-000000000001')), _negated=True), ('allows_negative_balance', False), ('handle__regex', '^[a-z0-9_]{3,20}$')), _connector='OR'), name='account_funding_or_valid_user')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(db_index=True)),
                ('operation_type', models.CharField(max_length=20)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='persistence.accountmodel')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_entries', to='persistence.accountmodel')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('currency', 'COP')), name='ledger_currency_cop'), models.CheckConstraint(condition=models.Q(('amount_minor', 0), _negated=True), name='ledger_nonzero_amount'), models.UniqueConstraint(fields=('operation_id', 'account'), name='ledger_operation_account_unique')],
            },
        ),
    ]
