# Generated by Django 5.2.17 on 2026-09-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_external_funding_and_immutable_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOperationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('operation_id', models.UUIDField(unique=True)),
                ('source_balance_minor', models.DecimalField(decimal_places=0, max_digits=40, null=True)),
                ('destination_balance_minor', models.DecimalField(decimal_places=0, max_digits=40, null=True)),
                ('currency', models.CharField(default='COP', max_length=3)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idempotency_key',), name='transfer_idempotency_key_unique'), models.CheckConstraint(condition=models.Q(('currency', 'COP')), name='transfer_currency_cop')],
            },
        ),
    ]
