# Generated by Django 5.2.17 on 2026-09-24 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpenseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='persistence.accountmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_minor', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_participations', to='persistence.accountmodel')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='persistence.sharedexpensemodel')),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
        migrations.AddField(
            model_name='transferoperationmodel',
            name='shared_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='persistence.sharedexpensemodel'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpensemodel',
            constraint=models.CheckConstraint(condition=models.Q(('total_minor__gt', 0)), name='expense_positive_total'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpensemodel',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'COP')), name='expense_currency_cop'),
        ),
        migrations.AddConstraint(
            model_name='participantmodel',
            constraint=models.UniqueConstraint(fields=('expense', 'account'), name='expense_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='participantmodel',
            constraint=models.CheckConstraint(condition=models.Q(('share_minor__gt', 0)), name='participant_positive_share'),
        ),
    ]
